### ISSUE TITLE
eventmap sketching (menu design)

### ISSUE THREAD

**Issue by Sabse** [Sabse/RefugeeSimulator#3]
Die Eventmap stellt das zentrale Menü für die Manipulierung des Levels dar. Sie ermöglicht dem Therapeuten Events einzufügen und den Zeitpunkt der Auslösung zu bestimmen. 
Das Layout umfasst folgende Kriterien:
- Abbildung des Levels aus Vogelperspektive (für Prototyp nur Sketch)
- Darstellung der Position des Spielers in Echtzeit
- Darstellung der platzierten Events
- Öffnen des Event-Auswahl-Menüs durch Interaktion mit der Eventmap

**Comment by MaxMueller0815** [comment]
Videos von leuten, die etwas ähnliches umgesetzt haben:
https://www.youtube.com/watch?v=1kb45pPd90M

https://www.youtube.com/watch?v=9U1m_14LUOo

Forum Einträge zu ähnlichen Projekten:
https://forums.unrealengine.com/showthread.php?59398-Easy-Offscreen-Indicator-Blueprint-Node

https://forums.unrealengine.com/showthread.php?80816-M-O-S-Markable-Objects-System
